import image1 from "./assets/PatekImages/1.png";
import image2 from "./assets/PatekImages/2.png";
import image3 from "./assets/PatekImages/3.png";
import image4 from "./assets/PatekImages/4.png";
import image5 from "./assets/PatekImages/5.png";
import image6 from "./assets/PatekImages/6.png";
import image7 from "./assets/PatekImages/7.png";
import image8 from "./assets/PatekImages/8.png";
import image9 from "./assets/PatekImages/9.png";
import image10 from "./assets/PatekImages/10.png";
import image11 from "./assets/PatekImages/11.png";
import image12 from "./assets/PatekImages/12.png";
import image13 from "./assets/PatekImages/13.png";
import image14 from "./assets/PatekImages/14.png";
import image15 from "./assets/PatekImages/15.png";
import image16 from "./assets/PatekImages/16.png";
import image17 from "./assets/PatekImages/17.png";
import image18 from "./assets/PatekImages/18.png";
import image19 from "./assets/PatekImages/19.png";

export const PatekData = [
  {
    id: 1,
    bezel: "Platinum",
    caseMaterial: "Stainless Steel",
    caseSize: "35 MM",
    dialColor: "Gray",
    productName: "Yacht Master",
    price: 4900,
    productImage: image1,
  },
  {
    id: 2,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "36 MM",
    dialColor: "Gray",
    productName: "Oyster Perpetual",
    price: 7400,
    productImage: image2,
  },
  {
    id: 3,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "36 MM",
    dialColor: "Black",
    productName: "Explorer",
    price: 7800,
    productImage: image3,
  },
  {
    id: 4,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "40 MM",
    dialColor: "Black",
    productName: "Submariner",
    price: 9100,
    productImage: image4,
  },
  {
    id: 5,
    bezel: "18K White Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "36 MM",
    dialColor: "Green",
    productName: "Datejust",
    price: 10500,
    productImage: image5,
  },
  {
    id: 6,
    bezel: "18K Yellow Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "40 MM",
    dialColor: "Blue",
    productName: "Submariner",
    price: 11200,
    productImage: image6,
  },
  {
    id: 7,
    bezel: "18K White Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "36 MM",
    dialColor: "Gray",
    productName: "Datejust",
    price: 11500,
    productImage: image7,
  },
  {
    id: 8,
    bezel: "18K White Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "41 MM",
    dialColor: "Blue",
    productName: "Datejust",
    price: 12600,
    productImage: image8,
  },
  {
    id: 9,
    bezel: "18K Yellow Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "41 MM",
    dialColor: "Champagne",
    productName: "Datejust",
    price: 13800,
    productImage: image9,
  },
  {
    id: 10,
    bezel: "18K Yellow Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "41 MM",
    dialColor: "Silver",
    productName: "Datejust",
    price: 13950,
    productImage: image10,
  },
  {
    id: 11,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "44 MM",
    dialColor: "Black, Blue",
    productName: "Sea Dweller Deepsea",
    price: 14500,
    productImage: image11,
  },
  {
    id: 12,
    bezel: "18K Rose Gold, Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "40 MM",
    dialColor: "Black",
    productName: "GMT-Master ii",
    price: 19500,
    productImage: image12,
  },
  {
    id: 13,
    bezel: "18K Yellow Gold",
    caseMaterial: "18K Yellow Gold",
    caseSize: "36 MM",
    dialColor: "Champagne",
    productName: "Day Date",
    price: 19500,
    productImage: image13,
  },
  {
    id: 14,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "40 MM",
    dialColor: "Black",
    productName: "Daytona",
    price: 20700,
    productImage: image14,
  },
  {
    id: 15,
    bezel: "18K Yellow Gold, Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "40 MM",
    dialColor: "Champagne",
    productName: "Daytona",
    price: 21400,
    productImage: image15,
  },
  {
    id: 16,
    bezel: "18K Yellow Gold",
    caseMaterial: "Stainless Steel",
    caseSize: "40 MM",
    dialColor: "Black",
    productName: "Daytona",
    price: 21800,
    productImage: image16,
  },
  {
    id: 17,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "41 MM",
    dialColor: "Multi-color, Turquoise",
    productName: "Oyster Perpetual",
    price: 25000,
    productImage: image17,
  },
  {
    id: 18,
    bezel: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseSize: "39 MM",
    dialColor: "Black",
    productName: "Sea Dweller",
    price: 29500,
    productImage: image18,
  },
  {
    id: 19,
    bezel: "18K Rose Gold",
    caseMaterial: "18K Rose Gold",
    caseSize: "42 MM",
    dialColor: "Gray",
    productName: "Sky Dweller",
    price: 35000,
    productImage: image19,
  },
];
